### ISSUE TITLE
Ruby 1.8.5 support

### ISSUE THREAD

**Issue by abh** [marcandre/backports#76]
I'm trying to use the "fpm" tool on CentOS / RHEL 5.x which is on Ruby 1.8.5. I've been led to believe that it's not working because 'backports' installs but doesn't actually work on 1.8.5. Is that right?

```
/usr/lib/ruby/gems/1.8/gems/clamp-0.6.0/lib/clamp/attribute/declaration.rb:36:in `append_to_args': undefined method `instance_variable_defined?' f
    from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.0/lib/clamp/parameter/parsing.rb:13:in `send'
    from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.0/lib/clamp/parameter/parsing.rb:13:in `parse_parameters'
    from /usr/lib/ruby/gems/1.8/gems/backports-3.3.0/lib/backports/tools.rb:117:in `each_without_optional_block'
    from /usr/lib/ruby/gems/1.8/gems/backports-3.3.0/lib/backports/tools.rb:117:in `each'
    from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.0/lib/clamp/parameter/parsing.rb:12:in `parse_parameters'
    from /usr/lib/ruby/gems/1.8/gems/backports-3.3.0/lib/backports/tools.rb:117:in `each_without_optional_block'
    from /usr/lib/ruby/gems/1.8/gems/backports-3.3.0/lib/backports/tools.rb:117:in `each'
    from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.0/lib/clamp/parameter/parsing.rb:10:in `parse_parameters'
    from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.0/lib/clamp/command.rb:55:in `parse'
    from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.0/lib/clamp/command.rb:68:in `run'
    from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.0/lib/clamp/command.rb:127:in `run'
    from /usr/lib/ruby/gems/1.8/gems/fpm-0.4.35/bin/fpm:8
    from /usr/bin/fpm:19:in `load'
    from /usr/bin/fpm:19
```
