### PR TITLE
Restore changelog 3.6.0-3.11.0

### PR DESCRIPTION
**Pull request by zverok**
In addition, I've added `require 'backports/version'` to `latest.rb`, because it is "lazy man's require all" file, and it SHOULD make backports version accessible. (In fact, I believe that any `require 'backports/*/*/*'` should make it accessible, probably... But that's another story.)

### CODE REVIEW

**Comment by marcandre** [comment]
Thanks for the PR.

For the ChangeLog: indeed, I forgot to keep it up to date. I prefer having the ChangeLog being only feature changes, not bug fixes (commit log is should be used for that).

I'll manually edit that commit, thanks

I now strongly advise against requiring `backports/latest` or `backports`. Moreover I'm very skeptical as to the usage of `Backports::VERSION`; please provide a good use for this.

**Comment by zverok** [comment]
> I now strongly advise against requiring `backports/latest` or `backports`. 

I understand your reasons, but they are not always actual. When I am coding just for fun, or in "turbo" mode (like let's drop in quick prototype/let's revive&refactor this 1000-years-old Rails project as quick as possible), it is proven to be pretty useful to have "just all modern Ruby features" at once, in one `require`. In fact, almost the only everyday thing that can't be ported is Ruby 2.3's `&.` operator, but I now mostly work with 2.3+ codebases anyways.

In fact, I've _never_ met with downsides of requiring entire backports at once, neither stability-wise, nor performance-wise.

> Moreover I'm very skeptical as to the usage of `Backports::VERSION`; please provide a good use for this.

Easy :) In fact, the real case that led to this entire PR, was this:

```ruby
> something.yield_self { something }
# => NoMethodError: undefined method `yield_self'
# hmmm... I thought I HAVE backports?..
> require 'backports'
# => false
# yeah, definitely have!

# Look into README: yep, yield_self backported
# Look into Changelog: damn
# Look into Rubygems: OK, new version is 3.11.0
> Backports::VERSION
# => 3.10.3

# Aha! Exit, update gem, read that `backports/latest` is the preferred way, enter
require 'backports/latest'
# => true
Backports::VERSION
# => NameError: uninitialized constant Backports::VERSION
# damn
```

BTW, in "require by feature" flow, I imagine this to be the "recommended" way in the future:
```ruby
require 'backports' # => what default gem 'backports' does. But requires NO parts, just version and maybe some tools
require 'backports/<version>/<feature>'
# => LoadError
# Hm, am I having an old version?..
Backports::VERSION
# => ...
```

Just thoughts. Whatever, closing this PR. Thanks for accepting the Changelog update.
